# Generated by Django 4.1.6 on 2023-03-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appname', models.CharField(max_length=50)),
                ('wattage', models.IntegerField()),
                ('gallons', models.IntegerField()),
            ],
        ),
    ]
