# Generated by Django 4.1.5 on 2023-03-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('wattage', models.IntegerField()),
                ('gallons', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Appliance',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
