# Generated by Django 4.1.5 on 2023-03-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appliancetype_delete_appliance_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplianceType',
            new_name='Appliance_Type',
        ),
    ]
