# Generated by Django 4.1.5 on 2023-03-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_air_quality_aperture_appliance_budget_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('watts_used', models.FloatField()),
                ('water_used', models.FloatField()),
                ('cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
