# Generated by Django 4.1.5 on 2023-03-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_eventlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventLog',
            new_name='Event_Log',
        ),
    ]
