# Generated by Django 4.1.5 on 2023-03-24 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_eventlog_event_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='log_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='api.event_log'),
            preserve_default=False,
        ),
    ]
