# Generated by Django 4.1.5 on 2023-03-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event_log_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
