# Generated by Django 4.1.5 on 2023-03-24 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('on_at', models.DateTimeField()),
                ('off_at', models.DateTimeField()),
                ('watts_used', models.FloatField()),
                ('water_used', models.FloatField()),
                ('cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('appliance_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.appliance')),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.event_log')),
            ],
        ),
    ]
