# Generated by Django 4.1.5 on 2023-03-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
