# Generated by Django 4.1.5 on 2023-03-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_appliance_type_gallons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperture',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
