# Generated by Django 4.1.5 on 2023-04-09 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_event_cost_alter_event_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='appliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.appliance'),
        ),
        migrations.AlterField(
            model_name='event',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.event_log'),
        ),
    ]
