# Generated by Django 4.1.5 on 2023-04-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_event_appliance_alter_event_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='off_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event_log',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event_log',
            name='water_used',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event_log',
            name='watts_used',
            field=models.FloatField(null=True),
        ),
    ]
