# Generated by Django 4.1.5 on 2023-04-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_event_off_at_alter_event_log_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='on_at',
            field=models.TimeField(),
        ),
    ]
