# Generated by Django 4.1.5 on 2023-04-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_event_on_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='on_at',
            field=models.DateTimeField(),
        ),
    ]
