# Generated by Django 4.1.5 on 2023-04-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('on_at', models.DateTimeField()),
                ('off_at', models.DateTimeField(null=True)),
                ('watts_used', models.FloatField(null=True)),
                ('water_used', models.FloatField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(null=True)),
                ('appliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.appliance')),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.event_log')),
            ],
        ),
    ]
