# Generated by Django 4.1.5 on 2023-04-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_thermostat_max_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='log',
        ),
        migrations.DeleteModel(
            name='Event_Log',
        ),
    ]
